[package]
name = "starcoin-resource-viewer"
version = "1.11.1-alpha"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
starcoin-vm-types = { path = "../types" }
move-binary-format = {git = "https://github.com/starcoinorg/move", rev = "9b9ad5016bbac7579808361e7bc1f63b3486ac69"  }
move-core-types = {git = "https://github.com/starcoinorg/move", rev = "9b9ad5016bbac7579808361e7bc1f63b3486ac69"  }
serde_json = "1.0"
serde = { version = "1.0.130", features = ["derive", "rc"] }
anyhow = "1.0.41"
hex = "0.4.3"
