[package]
name = "starcoin-move-explain"
version = "1.11.1-alpha"
authors = ["Diem Association <opensource@diem.org>"]
description = "Diem Move abort code explanations"
repository = "https://github.com/diem/diem"
homepage = "https://diem.org"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
clap = { version = "3", features = ["derive"] }
stdlib = { package="stdlib", path = "../stdlib"}
move-core-types = { git = "https://github.com/starcoinorg/move", rev = "0b4655469084eb2fb6b8a6a7690342d767f05e5b" }
bcs-ext = { package="bcs-ext", path = "../../commons/bcs_ext" }

[features]
default = []
