[package]
name = "starcoin-vm-runtime"
version = "1.11.1-alpha"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.41"
once_cell = "1.10.0"

starcoin-types = { path = "../../types"}
move-core-types = { git = "https://github.com/starcoinorg/move", rev = "9b9ad5016bbac7579808361e7bc1f63b3486ac69" }
move-vm-runtime = { git = "https://github.com/starcoinorg/move", rev = "9b9ad5016bbac7579808361e7bc1f63b3486ac69" }
move-stdlib = { git = "https://github.com/starcoinorg/move", rev = "9b9ad5016bbac7579808361e7bc1f63b3486ac69" }
tracing = "0.1.32"
starcoin-config = { path = "../../config"}
starcoin-logger = {path = "../../commons/logger"}
num_enum = "0.5.7"
crypto = { package = "starcoin-crypto", git = "https://github.com/starcoinorg/starcoin-crypto", rev = "d871dfb4216f034ee334a575926c101574d9d6dc"}
rand = "0.8.5"
rand_core = { version = "0.6.3", default-features = false }
bcs-ext = { package="bcs-ext", path = "../../commons/bcs_ext" }
stdlib = { package="stdlib", path = "../stdlib"}
starcoin-vm-types = { path = "../types"}
starcoin-move-compiler = { path = "../compiler"}
starcoin-natives = {path = "../natives"}
starcoin-metrics = {path = "../../commons/metrics"}

[dev-dependencies]

[features]
default = []
testing = ["move-stdlib/testing", "starcoin-natives/testing"]

